spring.application.name=cloud-dashboard

# Dynamic port for deployment (Render)
server.port=${PORT:8080}

# MongoDB Atlas connection
spring.data.mongodb.uri=mongodb+srv://anudeepgarlapati_db_user:2787@cluster0.zedqzom.mongodb.net/cloud_db?retryWrites=true&w=majority
